version: '3.8'

services:
  postgres:
    restart: always
    image: postgres
    container_name: "${DATABASE_CONTAINER_NAME}"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  php:
    container_name: "php-fpm"
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}  
    environment:
      # Symfony Config
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
      - APP_DEBUG=${APP_DEBUG}
    volumes:
      - ${APP_FOLDER}:/var/www/html

  nginx:
    container_name: "nginx"
    environment:
      HOSTNAME: ${HOSTNAME}
    build:
      context: ./docker/nginx
    volumes:
      - ${APP_FOLDER}:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "80:80"
